### ISSUE TITLE
Question about authentication

### ISSUE THREAD

**Issue by VictorAssis** [ecojuntak/api-gateway#1]
Hi Eko, i read your article and helped me a lot, but i have a question. If the microservice needs to know the user, what is the best approach?

Replicate the JWT secret in all services to get the user? Send the user decoded to the service? Or other option?

Thanks for the help

**Comment by ecojuntak** [comment]
Hi @VictorAssis, thank you for asking about it.

In my opinion, the better approach is to send the decoded JWT to the services that need it. Why?
1. You only need to maintain one JWT secret. Easy to rotate, easy to maintain.
2. Your other services focus to do their task. Let say you have Book Service. The Book Service's task is only to serve data in its domain, which is every use case related to book. If you replicate the JWT secret to User Service you will force the Book Service to do authentication, which is not its task. Single responsibility principle.

Why not replicate the JWT secret across all services? 
1. As your services scaling, you need to maintain all the secret, make one same to others. 
2. How about when you need to change the JWT secret? Definitely, you need to update the JWT secret across all your services. 
3. Maybe later you also need to make regular key roration and that was painful to update it manually, or you need to make an automation to rotate all the key. Need extra work, right?
4. Breaking the single responsibility principle, just like I already illustrated above.

In another side, the solution that proposes also have a drawback. How if someone can intercept your request, which is contained plain user data? You will end. But, there also a solution for this that you can use a secure protocol to reduce the possibility of request interception, as simple as using HTTPS across all the services.

Those examples are just very basic I think. So, you can choose, setup secure protocol or your JWT secret across all your services?
Just tell me if you have others approach, love to discuss deeper.

**Comment by VictorAssis** [comment]
Thanks for the answer!

I readed a thousand of articles about this theme in the last days hahaha.

This article by Mina Ayoub (https://medium.com/tech-tajawal/microservice-authentication-and-authorization-solutions-e0e5e74b248a) show differents approachs, but in my case it's more effective the approach used by you.

We decide to do the authentication in gateway, decoding the JWT and passing the user`s JSON as string by header to the services. And, to not sobrecarregate the gateway, the own service gonna do the authorization when they need.

To protect our services, we gonna build a demilitarized zone, where just the gateway can request.
